# Generated by Django 4.1.3 on 2022-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0003_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='thumbnail',
            field=models.ImageField(upload_to='certificates/'),
        ),
    ]
