# Generated by Django 4.1.3 on 2022-11-12 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0005_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='thumbnail',
            field=models.ImageField(upload_to='achievements/'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=254)),
                ('years_of_experience', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('coach_avatar', models.ImageField(blank=True, null=True, upload_to='coachavatars/')),
                ('achievements', models.ManyToManyField(to='coachMe.achievement')),
                ('certifications', models.ManyToManyField(to='coachMe.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
