# Generated by Django 4.1.3 on 2022-11-12 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0008_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='clientavatars/'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('C', 'Cancelled')], max_length=1)),
                ('mode', models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('UPI', 'UPI')], max_length=3)),
                ('date', models.DateField()),
                ('remark', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('P', 'Purchase'), ('R', 'Reverse')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.client')),
            ],
        ),
    ]
