# Generated by Django 4.1.3 on 2022-11-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0015_alter_package_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('UPI', 'UPI'), ('ND', 'Not Defined')], max_length=3),
        ),
    ]
