# Generated by Django 4.1.3 on 2022-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0020_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default=None, max_length=1000000),
        ),
    ]
