# Generated by Django 4.1.3 on 2022-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0022_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
