# Generated by Django 4.1.3 on 2022-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('thumbnail', models.ImageField(upload_to='certificates/% Y/% m/% d/')),
            ],
        ),
    ]
