# Generated by Django 4.1.3 on 2022-11-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0004_alter_certificate_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('thumbnail', models.ImageField(upload_to='achievement/')),
            ],
        ),
    ]
