# Generated by Django 4.1.3 on 2022-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0012_alter_client_end_date_alter_client_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
