# Generated by Django 4.1.3 on 2022-11-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0014_mapping_remove_client_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.coach'),
        ),
    ]
