# Generated by Django 4.1.3 on 2022-11-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0016_alter_transaction_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=254)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('neck_inches', models.FloatField()),
                ('shoulder_inches', models.FloatField()),
                ('waist_inches', models.FloatField()),
                ('quads_inches', models.FloatField()),
                ('calf_inches', models.FloatField()),
                ('daily_act_level', models.IntegerField()),
                ('gym_join', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('curr_workout_patt', models.TextField()),
                ('pref_workout_time', models.CharField(max_length=100)),
                ('avg_sleeping_hours', models.FloatField()),
                ('sleep_quality', models.IntegerField()),
                ('stress_levels', models.IntegerField()),
                ('any_diff_mov', models.TextField()),
                ('health_related_issues', models.TextField()),
                ('supps', models.TextField()),
                ('anabolics', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('anabolics_desc', models.TextField()),
                ('past_curr_injuries', models.TextField()),
                ('veg_non_veg', models.CharField(choices=[('V', 'Veg'), ('N', 'Non Veg')], max_length=1)),
                ('no_of_meals', models.TextField()),
                ('curr_eating_pattern', models.TextField()),
                ('cheat_meals', models.TextField()),
                ('easily_reach_food', models.TextField()),
                ('curr_physique_pic', models.ImageField(blank=True, null=True, upload_to='current physique/')),
                ('expectations_from_caoch', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.coach')),
            ],
        ),
    ]
