# Generated by Django 4.1.3 on 2022-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0017_clientonboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboard',
            name='chest_inches',
            field=models.FloatField(null=True),
        ),
    ]
