# Generated by Django 4.1.3 on 2022-11-13 16:00

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0009_client_client_avatar_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Coach'), ('L', 'Client')], max_length=1, null=True),
        ),
    ]
