# Generated by Django 4.1.3 on 2022-11-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0010_user_phone_no_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_package_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='package_desc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='price_paid',
        ),
        migrations.CreateModel(
            name='PackageCoachMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.coach')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.package')),
            ],
        ),
    ]
