# Generated by Django 4.1.3 on 2022-11-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0013_alter_transaction_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='PackageCoachMapping',
        ),
        migrations.AddField(
            model_name='mapping',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.client'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.coach'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachMe.package'),
        ),
    ]
