# Generated by Django 4.1.3 on 2022-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachMe', '0023_message_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
